uploads = []
outputs = []

[[generated]]
id = "-yevYkJSVt3XhPDEMUyar"
uri = "file://artifacts/nocmf-website/public/images/impact.png"
type = "image"
title = "generated_image"

[[generated]]
id = "0g90Qjz-TJCigqt8ytcfN"
uri = "file://artifacts/nocmf-website/public/images/logo-traderjoes.png"
type = "image"
title = "generated_image"

[[generated]]
id = "s-W9om7cTmkQJBRfpZ5Y1"
uri = "file://artifacts/nocmf-website/public/images/logo-costco.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ebA8yaZ3jnekYlVdCXz8l"
uri = "file://artifacts/nocmf-website/public/images/logo-starbucks.png"
type = "image"
title = "generated_image"
